const ManualPage = () => {
  return (
    <>
      <div className="flex flex-col h-full p-6 bg-white 2xl:ml-4 ml-0 sm:ml-8 sm:mr-8 mr-0 sm:rounded-2xl rounded-none shadow-lg hover:shadow-xl transition-all">
        <p className="text-lg font-roboto font-bold">
          Manual
          <span className="block text-xs font-roboto text-gray-500 font-normal">
            User instructions and best practices
          </span>
        </p>
        <div className="collapse-title text-lg font-bold font-roboto pl-0">
          Configuration Panel
        </div>
        <div className="join join-vertical w-full font-roboto bg-primary text-white">
          <div className="collapse collapse-arrow join-item border-base-300 border">
            <input type="radio" name="my-accordion-4" defaultChecked />
            <div className="collapse-title text-sm font-medium">
              Custom Drop-Down Content
            </div>
            <div className="collapse-content text-xs">
              <p>
                This feature allows users to input and manage their own specific
                emission sources related to their organization. Once the custom
                data is imported, it will be available in a drop-down menu for
                easy selection of the desired emission source. The custom list
                file can be generated using the OCF Lite Tool, which is
                currently under development. Please note that if the uploaded
                file does not adhere to the required format, an error message
                will be shown, prompting the user to correct the issue.
                Additionally, custom lists are session-specific and will not be
                saved or carried over between sessions. This ensures that each
                session starts with a clean slate, requiring the user to
                re-upload their custom lists if needed.
              </p>
            </div>
          </div>
          <div className="collapse collapse-arrow join-item border-base-300 border">
            <input type="radio" name="my-accordion-4" />
            <div className="collapse-title text-sm font-medium">
              Import Previous Data
            </div>
            <div className="collapse-content text-xs">
              <p>
                This feature allows users to reload data they have previously
                created and downloaded. Users can upload a JSON file,
                specifically generated by the app, which contains their custom
                data entries. This data is then reloaded into the application's
                tables, enabling users to continue working with their existing
                data without having to re-enter it. <br />
                <br />
                To use this feature, users should first create and manage their
                data within the app's table interface. Once satisfied, they can
                download their data in a JSON format directly from the app. This
                file can later be re-imported using the "Import Previous Data"
                option, ensuring that all previously saved data is restored and
                available for further editing or analysis. <br />
                <br />
                The app automatically validates the structure of the uploaded
                JSON file, ensuring compatibility. If the file is not in the
                correct format or contains errors, the system will alert the
                user with an appropriate error message, prompting them to upload
                a correct file. <br />
                <br />
                This feature is designed for session continuity and data
                recovery. When you load the data, it will persist across
                sessions by being stored in your browser's local storage. This
                means that if you make changes to the data, those changes will
                be saved automatically and remain available when you return to
                the app. However, these changes will only be stored locally and
                will not update the original JSON file. If you wish to retain
                the changes permanently, you must download the updated table
                with the new data. <br />
                <br />
                This functionality is ideal for users who need to pause and
                resume their work, providing a seamless way to manage and reload
                their custom data within the app. The local storage feature
                ensures that your data remains intact between sessions, allowing
                you to continue working seamlessly. <br /> <br />
                However, to fully leverage this data, especially for calculating
                your carbon footprint, as well as related analyses,
                visualizations, and reporting, you will need to use the OCF Lite
                Tool, which is specifically designed to process this JSON file.
                Remember to download your data if you need to create a backup or
                share it with your organization’s administrator, who holds the
                OCF Lite Tool license. <br /> <br />
              </p>
            </div>
          </div>
          <div className="collapse collapse-arrow join-item border-base-300 border">
            <input type="radio" name="my-accordion-4" />
            <div className="collapse-title text-sm font-medium">
              Add Optional Details
            </div>
            <div className="collapse-content text-xs">
              <p>
                The Optional Data Section is designed to help users of the OCF
                Lite Tool easily identify the origin of the data and streamline
                data aggregation processes within the tool. This section allows
                users to input additional details such as the country of origin,
                the company's name, the user's full name, and their job email
                address. By providing this optional information, users can
                ensure that their data is more organized and traceable,
                facilitating more efficient processing and analysis when the
                data is imported into the OCF Lite Tool. The details entered in
                this section are stored in the browser's local storage, allowing
                them to persist across sessions. This means that the information
                will be automatically populated the next time the user accesses
                the app, reducing the need to re-enter the same data repeatedly.
              </p>
            </div>
          </div>
        </div>
        <div className="collapse-title text-lg font-bold font-roboto pl-0">
          Data Table
        </div>
        <div className="join join-vertical w-full font-roboto bg-primary text-white">
          <div className="collapse collapse-arrow join-item border-base-300 border">
            <input type="radio" name="my-accordion-4" />
            <div className="collapse-title text-sm font-medium">
              Data input section
            </div>
            <div className="collapse-content text-xs">
              <p>
                The Data Input Section is a critical component of the web app
                that allows users to input custom data related to emissions and
                consumption for carbon footprint calculations. This section is
                designed with a structured form that guides users through the
                process of adding data in a systematic and organized manner.
                <br /> <br />
                Key Features: <br /> <br />
                <span className="font-bold">Scope Selection:</span> Users start
                by selecting the appropriate scope (e.g., Scope 1, Scope 2,
                Scope 3) from a dropdown menu. This selection defines the
                context for the data being entered.
                <br /> <br />{" "}
                <span className="font-bold">Activity Selection:</span> After
                choosing a scope, users can select an activity related to that
                scope. The available activities are dynamically populated based
                on the selected scope.
                <br /> <br />{" "}
                <span className="font-bold">
                  Emission Source Selection:
                </span>{" "}
                Users then choose an emission source associated with the
                selected activity. This dropdown is also dynamically updated
                based on the prior selections, ensuring relevance and accuracy.
                <br /> <br />{" "}
                <span className="font-bold">Consumption Input:</span> Users
                input the amount of consumption related to the selected emission
                source. The input field accepts numerical values and includes
                validation to ensure the data is entered correctly.
                <br /> <br /> <span className="font-bold">
                  Unit Selection:
                </span>{" "}
                Users select the unit of measurement for the consumption data.
                The available units are context-sensitive, based on the emission
                source and activity.
                <br /> <br />{" "}
                <span className="font-bold">Data Source Input:</span> Users are
                prompted to enter the source of the data, providing traceability
                and credibility to the information entered.
                <br /> <br /> <span className="font-bold">
                  Add Button:
                </span>{" "}
                Once all fields are filled out correctly, users can click the
                "Add" button to submit the data. The app validates the entries
                before adding them to the table, ensuring all required
                information is provided and correctly formatted.
                <br /> <br /> This section is integral to the data entry
                process, ensuring that users can efficiently input and manage
                the data needed for subsequent analysis in the app.
              </p>
            </div>
          </div>
          <div className="collapse collapse-arrow join-item border-base-300 border">
            <input type="radio" name="my-accordion-4" />
            <div className="collapse-title text-sm font-medium">
              Table - data structure and utilities
            </div>
            <div className="collapse-content text-xs">
              <p>
                Data table provides a comprehensive interface for viewing,
                managing, and manipulating the data entered in the app. This
                section displays the data in a structured table format and
                includes several utilities to enhance data management.
                <br /> <br /> Key Features: <br /> <br />
                <span className="font-bold">Data Table Display:</span> The table
                lists all data entries with columns for Scope, Activity,
                Emission Source, Consumption, Unit, and Data Source. This layout
                allows users to easily view and analyze their data in a
                structured manner.
                <br /> <br /> <span className="font-bold">
                  Row Deletion:
                </span>{" "}
                Users can delete individual rows from the table using the delete
                button, which is represented by a trash icon.
                <br /> <br />{" "}
                <span className="font-bold">Restore Last Change:</span> If a row
                is mistakenly deleted, users can use the "Restore Last Change"
                button to undo the last deletion. This utility ensures that data
                loss due to accidental deletions can be easily recovered.
                <br /> <br />{" "}
                <span className="font-bold">Search Functionality:</span> The
                table includes a search feature that allows users to filter the
                data based on keywords. This helps in quickly locating specific
                entries without manually scrolling through the entire table.
                <br /> <br />{" "}
                <span className="font-bold">Remove All Button:</span> For
                clearing all data from the table, users can click the "Remove
                All" button. This action is useful when users need to start over
                or remove outdated data. The app allows users to restore all
                data if this action was performed mistakenly.
                <br /> <br />{" "}
                <span className="font-bold">Download to File:</span> Users can
                export the entire table's data into a JSON file by clicking the
                "Download to file" button. This feature is essential for
                creating backups, sharing data, or importing it into other tools
                like the OCF Lite Tool for further analysis.
                <br /> <br />{" "}
                <span className="font-bold">Persistent Data:</span> The app
                automatically saves the table data in the browser's local
                storage, ensuring that the data remains available across
                sessions. Users can pick up where they left off without needing
                to re-enter data. <br /> <br /> This section is vital for
                managing and interacting with the data collected in the app,
                providing users with the tools necessary for effective data
                handling and ensuring accuracy and convenience in their
                workflow.
              </p>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default ManualPage;
